TZ from env, client log, alpine 3.14, path DB changed.
Py-KMS-Organization/py-kms pull request #13
Opened 2021-10-15 00:01 UTC by edgd1er

May be too many change for a single PR. this is still a work in progress as I wish to run as user py-kms with specific uid/gid.
Please note that also database path has been changed to allow volume or file mounting: /db/pykms_database.db
+ 3 python libs updates due to security fix.

2021-10-30 09:33 UTC, simonmicro commented
Okay, I'm still not 100% percent conform with the new `start.py` but whatever - let's ignore that. But still please integrate https://github.com/Py-KMS-Organization/py-kms/commit/4ee742d671ae853f600b90425c97b2080ff17b80 and https://github.com/Py-KMS-Organization/py-kms/commit/677916a3ec9964b119b6478f1a45e484bc603433 of the current upstream, because this makes the script at least some sort more readable (and you have somehow dropped the `os.makedirs()` instruction. After that: I'll hit "merge" faster than you can comment it! :smile:

2021-10-30 09:36 UTC, simonmicro requested changes

2021-10-30 09:36 UTC, simonmicro commented on docker/start.py
> +    loggersrv.info("Storing database file to %s" % dbPath)
Please add https://github.com/Py-KMS-Organization/py-kms/commit/4ee742d671ae853f600b90425c97b2080ff17b80

2021-10-30 09:36 UTC, simonmicro commented on docker/start.py
> +    client_cmd = [PYTHON3, '-u', 'pykms_Client.py', os.environ.get('IP', "0.0.0.0"), os.environ.get('PORT', 1688),
And also here https://github.com/Py-KMS-Organization/py-kms/commit/4ee742d671ae853f600b90425c97b2080ff17b80

2021-10-30 10:45 UTC, edgd1er commented
changes are implemented. as a side-note, I'm not sure being able to change listening port for kms and websqlite is very useful. Being in a container, ports are reassigned, except when network is inhost-mode.

2021-10-30 16:48 UTC, Matthew-Beckett commented
> changes are implemented. as a side-note, I'm not sure being able to change listening port for kms and websqlite is very useful. Being in a container, ports are reassigned, except when network is inhost-mode.

Can you expand on that part about the port reassignment? Docker ports are configurable and static in my experience.

2021-10-30 17:39 UTC, edgd1er commented
> > changes are implemented. as a side-note, I'm not sure being able to change listening port for kms and websqlite is very useful. Being in a container, ports are reassigned, except when network is in host-mode.
> 
> Can you expand on that part about the port reassignment? Docker ports are configurable and static in my experience.

for me, internal port = port exposed inside the container, external port is the port exposed on the host.

when using bridge mode, an "external" port is mapped to the "internal" port: docker run -p 1080:8080 ... => access through host_ip:1080
when using host mode, only the exposed port(s), formerly the internal one is used: docker run -d --network host .... => access through host_ip:8080

As far as I know, most usage are in bridge mode to have network isolation, as such, changing internal ports are useless.
kms_server has port assignement as it may also be executed without docker, and then ports assignements might be useful.

websqlite is defined only in the container, defining internal port (inside the container) has no use when running in bridge mode. 

The question: do we need to give the opportunity to define (and maintain) the "internals" ports ( kms, web sqlite) feature, knowing most of the time, the container will be running in bridge mode ?

I might be wrong assuming host mode is rarely used.

2021-10-30 17:41 UTC, Matthew-Beckett commented
> > > changes are implemented. as a side-note, I'm not sure being able to change listening port for kms and websqlite is very useful. Being in a container, ports are reassigned, except when network is in host-mode.
> 
> > 
> 
> > Can you expand on that part about the port reassignment? Docker ports are configurable and static in my experience.
> 
> 
> 
> for me, internal port = port exposed inside the container, external port is the port exposed on the host.
> 
> 
> 
> when using bridge mode, an "external" port is mapped to the "internal" port: docker run -p 1080:8080 ... => access through host_ip:1080
> 
> when using host mode, only the exposed port(s), formerly the internal one is used: docker run -d --network host .... => access through host_ip:8080
> 
> 
> 
> As far as I know, most usage are in bridge mode to have network isolation, as such, changing internal ports are useless.
> 
> kms_server has port assignement as it may also be executed without docker, and then ports assignements might be useful.
> 
> 
> 
> websqlite is defined only in the container, defining internal port (inside the container) has no use when running in bridge mode. 
> 
> 
> 
> The question: do we need to give the opportunity to define (and maintain) the "internals" ports ( kms, web sqlite) feature, knowing most of the time, the container will be running in bridge mode ?
> 
> 
> 
> I might be wrong assuming host mode is rarely used.

I understand what you mean now, I agree with you.

2021-10-31 14:10 UTC, simonmicro commented
It is just the same philosophy for the ports as also for your uid/gid reassignment. After all docker allows you to remap our default docker uid of 1000 to any other arbitrary id as you need. But beside that the port specification could be really interesting in case you have to use the host networking mode - e.g. in case you run on a swarm and do not want to utilize load-balancing and be only available on an specific node.

2021-10-31 14:14 UTC, simonmicro commented
Okay, let's hope this does not break anything!

2021-10-31 14:14 UTC, merged

2021-10-31 14:20 UTC, simonmicro commented
Aaand the Dockerfile is broken. @edgd1er please fix this and test it this time.